### PR TITLE
added typescript folder

### PR DESCRIPTION
**Pull request by con-ssc**
added typings for xrm, node, es6-shim
added typings to ignore
transpiled js to ts

### CODE REVIEW

**Comment by davidyack** [comment]
Just FYI so you didn't think we forgot about this.  We are looking at how best to incorporate Typescript in.   Thanks for submitting this it helps move things along

**Comment by rappen** [comment]
Crossing my fingers you will find a good way forward with this! 👍

**Comment by davidyack** [comment]
Well, it will move forward the key things being considered is

1) Do we have the right typing on the method signatures - I would prefer to not break once we publish anymore than we have to.  

2) Do we first release a TS definition or do we jump straight to maintaining the JavaScript in TS - From a consumption point of view I don't think it would really matter it would only matter for ongoing maintenance

**Comment by con-ssc** [comment]
Just let me know if you need my support.

**Comment by davidyack** [comment]
Rather than keep this hanging around closing for now- we have the TS Defintion and will consider in the future

**Pull request closed without merging**
